fix usage of click.BadOptionUsage
click.BadOptionUsage expects the name of the option as the first
argument (which was not provided). E.g. if a configuration file was not
present, this resulted in errors like the following:

    Error: <click.core.Context object at 0x10c6b9e80>

Instead, when using it as designed, the error message becomes
isgnificantly more helpful:

    Error: Error reading configuration file: [Errno 2] No such file or directory: 'abc.yam'